### ISSUE TITLE
Problem connecting opcua server to datahub

### ISSUE THREAD

**Issue by soyEvaristo** [umati/Showcase#22]
Trying to connect an OPC UA server to the datahub through the application https://fairconnect.umati.app/owner

We keep getting this error on the app:

{
"connectivity": "Not OK",
"endpoint": "10.80.0.86:4840",
"time": "Tue Mar 30 15:57:47 UTC 2021",
"error": "UaServiceFaultException: status=Bad_IdentityTokenInvalid, message=The user identity token is not valid."
}

We ve disabled every firewall / antivirus between both applications. We ve also checked that other clients connect successfully to the server (UAExpert, Prosys, OPCSampleClient). If you could give us some input to solve this issue.

Thanks in advance.

**Comment by wgaofei** [comment]
Excuse me, how did you solve it? I'm running into this issue as well

**Comment by wlkrm** [comment]
@wgaofei the datahub no longer exists. Please get in touch with @GoetzGoerisch for the new onboarding process.
